config/routes.rb
Twittexplorer::Application.routes.draw do
  root to: 'articles#index'
  resources :articles do
    collection { get :search }
    member { get :translate }
  end

end

app/models/article.rb
require 'google_drive'

class Article < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  include Elasticsearch::Model::Indexing

  ELASTICSEARCH_MAX_RESULTS = 25

  mapping do
    indexes :location,      type: 'geo_point'
    indexes :lang,          type: 'string'
    indexes :content,       type: 'string'
    indexes :uuid,          type: 'string'
    indexes :published_on,  type: 'integer'
    indexes :user,          type: 'string'
    indexes :project,       type: 'string'
    indexes :is_private,    type: 'boolean'
    indexes :is_removed,    type: 'boolean'
    indexes :has_photo,     type: 'boolean'
    indexes :has_instagram, type: 'boolean'
  end

  def as_indexed_json(_options = {})
    as_json(only: %w(content lang uuid published_on user is_private is_removed has_photo has_instagram project))
    .merge(location: {
      lat: lat.to_f,
      lon: lon.to_f
    })
  end

  def self.search(params)
    query = params[:q]
    options = params || {}
  
    # define search definition
    search_definition = {
      query: {
        bool: {
          must: [
            { term: { is_private: ActiveRecord::ConnectionAdapters::Column.value_to_boolean(params[:is_private]) } },
            { term: { is_removed: ActiveRecord::ConnectionAdapters::Column.value_to_boolean(params[:is_removed]) } },
            { term: { has_photo: ActiveRecord::ConnectionAdapters::Column.value_to_boolean(params[:has_photo]) } },
            { term: { has_instagram: ActiveRecord::ConnectionAdapters::Column.value_to_boolean(params[:has_instagram]) } },
            { term: { project: params[:project] } }
          ]
        }
      }
    }
  
    search_definition[:from] = params[:page].to_i * ELASTICSEARCH_MAX_RESULTS
    search_definition[:size] = ELASTICSEARCH_MAX_RESULTS

    # query
    if query.present?
      search_definition[:query][:bool][:must] << {
        multi_match: {
          query: query,
          fields: %w(lang content uuid user),
          operator: 'and'
        }
      }
    end

    # geo spatial
    if options[:lat].present? && options[:lon].present?
      options[:distance] = 100 if options[:distance].blank?

      search_definition[:query][:bool][:must] << {
        filtered: {
          filter: {
            geo_distance: {
              distance: "#{options[:distance]}mi",
              location: {
                lat: options[:lat].to_f,
                lon: options[:lon].to_f
              }
            }
          }
        }
      }
    end

    # time
    if options[:from].present? && options[:to].present?

      search_definition[:query][:bool][:must] << {
        filtered: {
          filter: {
            range: {
              published_on: {
                lte: Time.parse(options[:to]).to_i,
                gte: Time.parse(options[:from]).to_i
              }
            }
          }
        }
      }
    end

    puts search_definition.inspect

    __elasticsearch__.search(search_definition)
  end

  def url
    'https://twitter.com/' + self.user + '/status/' + self.uuid
  end

  def translate
    w = self.get_worksheet
    row = w.num_rows + 1
    w[row, 1] = self.content
    w[row, 2] = self.url
    w.save
  end

  def added_to_spreadsheet?
    w = self.get_worksheet
    for row in 2..w.num_rows
      if w[row, 2] == self.url
        return true
      end
    end
    false
  end

  protected

  def get_worksheet
    session = spreadsheet = nil
    key = CONFIG['google_id']

    begin
      access_token = Rails.cache.fetch('!google_access_token') do
        generate_google_access_token
      end
      session = GoogleDrive.login_with_oauth(access_token)
      spreadsheet = session.spreadsheet_by_key(key)
    rescue Google::APIClient::AuthorizationError
      access_token = generate_google_access_token
      Rails.cache.write('!google_access_token', access_token)
      session = GoogleDrive.login_with_oauth(access_token)
      spreadsheet = session.spreadsheet_by_key(key)
    end

    w = spreadsheet.worksheet_by_title(self.project)
    if w.nil?
      w = spreadsheet.add_worksheet(self.project)
      w.save
      w[1, 1] = 'source_text'
      w[1, 2] = 'link'
      w[1, 3] = 'translation'
      w[1, 4] = 'comment'
      w[1, 5] = 'translator name'
      w[1, 6] = 'translator web site'
      w[1, 7] = 'commenter'
      w[1, 8] = 'commenter web site'
      w.save
    end
    w
  end

  private

  def generate_google_access_token
    require 'google/api_client'
    require 'google/api_client/client_secrets'
    require 'google/api_client/auth/installed_app'
    
    client = Google::APIClient.new(
      :application_name => 'Twittexplorer',
      :application_version => '1.0.0'
    )
    
    key = Google::APIClient::KeyUtils.load_from_pkcs12(CONFIG['google_pkcs12_path'], CONFIG['google_pkcs12_secret'])
    client.authorization = Signet::OAuth2::Client.new(
      :token_credential_uri => 'https://accounts.google.com/o/oauth2/token',
      :audience => 'https://accounts.google.com/o/oauth2/token',
      :scope => ['https://www.googleapis.com/auth/drive', 'https://spreadsheets.google.com/feeds/'],
      :issuer => CONFIG['google_issuer'],
      :signing_key => key)
    client.authorization.fetch_access_token!
    client.authorization.access_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.search(params).records
    @message = ''
  end

  # GET /articles/search
  def search
    @articles = Article.search(params).records
    @message = ''
    render action: "index"
  end

  def translate
    a = Article.find(params[:id])
    if a.added_to_spreadsheet?
      @message = 'Already added to the spreadsheet'
    else
      a.translate
      @message = 'Added to the spreadsheet'
    end
    render text: "<p>#{@message}</p><p>&laquo; <a href=\"javascript:history.back(-1)\">Back</a></p><p><a href=\"https://docs.google.com/spreadsheets/d/#{CONFIG['google_id']}\" target=\"_blank\">See Spreadsheet</a></p>"
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render action: 'show', status: :created, location: @article }
      else
        format.html { render action: 'new' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def article_params
    params.require(:article).permit(:title, :content, :published_on, :lat, :lon, :lang)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :lon %>
  </div>
  <div class="field">
    <%= f.label :lang %><br>
    <%= f.text_field :lang %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Tweets</h1>

  <p>If you want to search by language, type <em>lang:<language code></em> in the <em>query</em> field below. Any other keyword will match the tweet content. You can also search by location, by using the latitude/longitude field below or by selecting a point on the map. You can also provide a distance from that point, and so only tweets in that radius will be returned.</p>

  <%= form_tag search_articles_path, method: 'get' do %>
    <%= label_tag :query %><br />
    <%= text_field_tag :q, params[:q], style: 'width: 100%' %>


    <div id="map" style="width: 100%; height: 350px;"></div>

    <p style="text-align: center;">
      <%= text_field_tag :lat, params[:lat], id: 'lat', style: 'width: 30%', placeholder: 'Latitude' %>
      <%= text_field_tag :lon, params[:lon], id: 'lon', style: 'width: 30%', placeholder: 'Longitude' %>
      <%= text_field_tag :distance, params[:distance], style: 'width: 30%', placeholder: 'Distance' %>
    </p>

    <p style="text-align: center;">
      <%= text_field_tag :from, params[:from], id: 'from', style: 'width: 30%', placeholder: 'From date', class: 'datepicker' %>
      <%= text_field_tag :to, params[:to], id: 'to', style: 'width: 30%', placeholder: 'To date', class: 'datepicker' %>
      <%= select_tag :project, options_for_select(Article.group(:project).map(&:project), params[:project]), id: 'project', style: 'width: 30%', prompt: 'Select a project' %>
    </p>

    <p style="text-align: center;">
      <%= check_box_tag :is_private, '1', params[:is_private] == '1' %> Private?
      <%= check_box_tag :is_removed, '1', params[:is_removed] == '1'%> Removed?
      <%= check_box_tag :has_photo, '1', params[:has_photo] == '1'%> Has photo?
      <%= check_box_tag :has_instagram, '1', params[:has_instagram] == '1'%> Has Instagram?
    </p>

    <p style="text-align: center;">
      <%= submit_tag :search, style: 'width: 6%' %>
    </p>
  <% end %>

<table style="width: 100%; border-collapse: collapse; text-align: center; border: 1px solid #333;">
  <thead>
    <tr>
      <th>Id</th>
      <th>User</th>
      <th>Content</th>
      <th>Language</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Date</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= link_to article.uuid, article.url, target: '_blank' %></td>
        <td><%= article.user %></td>
        <td><%= article.content %></td>
        <td><%= article.lang.to_s.gsub(/^lang:/, '') %></td>
        <td><%= article.lat %></td>
        <td><%= article.lon %></td>
        <td><%= Time.at(article.published_on) %></td>
        <td><span style="cursor: pointer" onclick="gmap_form({ lat: <%= article.lat %>, lon: <%= article.lon %>, lang: '<%= article.lang %>', content: '<%= article.content.gsub("'", "") %>', uuid: '<%= article.uuid %>', published_on: '<%= article.published_on %>', user: '<%= article.user %>' })">Show on the Map</span></td>
        <td><%= link_to('Translate', translate_article_path(article)) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<p style="text-align: center;"><%= link_to 'Load More', params.merge(page: params[:page].to_i + 1) %></p>
<p style="text-align: center;"><%= link_to 'See Spreadsheet', 'https://docs.google.com/spreadsheets/d/' + CONFIG['google_id'], target: '_blank' %></p>
<br>

<script>
  function gmap_form(point) {
    handler = Gmaps.build('Google');
    var lat;
    var lon;
    handler.buildMap({ provider: {}, internal: {id: 'map'}}, function() {
      if (point && point.lat && point.lon) {
        lat = point.lat;
        lon = point.lon;

        var embed = '<blockquote class="twitter-tweet">' + point.content + ' <a href="https://twitter.com/' + point.user + '/status/' + point.uuid + '">' + point.published_on + '</a></blockquote><p style="text-align: center;" id="loading-tweet"><em>Loading tweet...</em></p>';

        markers = handler.addMarkers([
          {
            "lat": point.lat,
            "lng": point.lon,
            "infowindow": embed
          }
        ]);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        handler.getMap().setZoom(12);
        document.getElementById("lat").value = point.lat;
        document.getElementById("lon").value = point.lon;
        _.each(markers, function(marker){
          google.maps.event.addListener(marker.getServiceObject(), 'click', function() {
            setTimeout(function() {
              twttr.widgets.load(); 
              document.getElementById('loading-tweet').style.display = 'none';
            }, 3000);
          });
        });
      }
      else {
        handler.fitMapToBounds();
        lat = parseFloat(document.getElementById('lat').value);
        lon = parseFloat(document.getElementById('lon').value);
        if (!lat || !lon) {
          if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(function(position) {
              lat = position.coords.latitude;
              lon = position.coords.longitude;
              handler.map.centerOn([lat, lon]);
              handler.getMap().setZoom(6);
            });
          }
        }
        else {
          document.getElementById("lat").value = lat;
          document.getElementById("lon").value = lon;
          handler.map.centerOn([lat, lon]);
          handler.getMap().setZoom(6);
        }
      }
    });

    var markerOnMap;

    function placeMarker(location) {
      if (markerOnMap) {
        markerOnMap.setPosition(location);
      }
      else {
        markerOnMap = new google.maps.Marker({
          position: location,
          map: handler.getMap()
        });
      }
    }

    google.maps.event.addListener(handler.getMap(), 'click', function(event) {
      placeMarker(event.latLng);
      document.getElementById("lat").value = event.latLng.lat();
      document.getElementById("lon").value = event.latLng.lng();
    });
  }

  gmap_form(null);
</script>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @article.content %>
</p>

<p>
  <strong>Published on:</strong>
  <%= @article.published_on %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twittexplorer</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry" %>
  <%= javascript_include_tag "//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
  <script>
    $(function() {
     $('.datepicker').datepicker({
       dateFormat: 'yy-mm-dd'
     });
    });
  </script>
</head>
<body>

<%= yield %>

</body>
</html>